[book]
authors = ["stuousk"]
language = "en"
multilingual = false
src = "src"
title = "bookmark"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding

# http:// 등으로 시작하는 링크를 자동으로 target=_blank 시켜주는 mdbook용 플러그인. https://crates.io/crates/mdbook-external-links
[preprocessor.external-links]