[book]
authors = ["stuousk"]
language = "en"
multilingual = false
src = "src"
title = "bookmark"

# http:// 등으로 시작하는 링크를 자동으로 target=_blank 시켜주는 mdbook용 플러그인. https://crates.io/crates/mdbook-external-links
[preprocessor.external-links]